### ISSUE TITLE
ElfSectionIter never returns the last section

### ISSUE THREAD

**Issue by mikiso1024** [rust-osdev/multiboot2-elf64#27]
Looks like there's an off-by-one error in the ElfSectionIter. Due to this, the last ELF section is never returned by the iterator.

The remaining_sections is initialized to number_of_sections - 1. In next(), when remaining_sections == 0, it returns none. So in a hypothetical kernel where number_of_sections was 1, next() would never return anything.

**Comment by Columbus240** [comment]
There is one test in `src/lib.rs` (`grub()`) that checks the behaviour of the `ElfSectionIter`. I don’t know the specifications well enough to understand what behaviour is expected or what the test actually does in detail. The test goes through all items the iterator returns and checks their values. It even checks for the final `None`. So either there is no off-by-one error as you describe (because of some behaviour expected by the specifications of ELF and Multiboot which neither you nor I know of), or the test expects the wrong behaviour of the code.

I don’t know ELF well enough to understand the relevant section in the Multiboot spec (3.4.7 in v1.6, 3.6.7 in v2.0), so I can’t help here.

Maybe @phil-opp who wrote the ELF code or @ahmedcharles who wrote the test know more about this.

Questions related to the test that might help coming to a conclusion:
* Why does the memory dump in the `bytes` array mention nine ELF symbol entries (section headers?) counted from zero to eight, but the ElfSectionIter `s` only returns seven of them (to me it seems they are the ones counted one to seven in the memory dump)?
* Why is there the address part of the ELF symbol entry 8 (referring to memory dump) overwritten with a pointer to `string_bytes` (in little-endian) at the start of the test?

**Comment by ahmedcharles** [comment]
The last section is always the same, it's a marker that there are no other sections. It's like a null terminated string, the null isn't part of the string.

**Comment by Caduser2020** [comment]
May this be closed, as the issue seems to be resolved? `ElfSectionIter` should not return the last section as it is a null section. See https://www.uclibc.org/docs/elf-64-gen.pdf for more info.
