### ISSUE TITLE
Docs? Code examples?

### ISSUE THREAD

**Issue by xacrimon** [rust-osdev/multiboot2-elf64#40]
Im having some trouble understanding how to use it and the source code in phil-opp's blog is out of date

**Comment by phil-opp** [comment]
Yeah, the documentation definitely needs work. For the old blog_os sources which use this library check out https://github.com/phil-opp/blog_os/tree/post_5.

**Comment by xacrimon** [comment]
Since I'm now a member of rust-osdev and due to the lack of docs I'll be writing documentation. If anyone wants to help out,  leave a comment here.

**Comment by mental32** [comment]
I've recently discovered and found this crate useful.

As of late I find myself currently looking through the source or the multiboot spec when I need to understand or find something since the documentation is a little absent.

@xacrimon I'm willing to help out, let me know if you had any specific changes in mind :D
