### ISSUE TITLE
i386 kernels cannot use MemoryMapTag safely

### ISSUE THREAD

**Issue by roblabla** [rust-osdev/multiboot2-elf64#49]
I'm currently writing an i386 kernel, and am using `multiboot2` to parse the multiboot2 information. Unfortunately, the MemoryMapTag returns the `start_address`/`end_address` as a usize, whereas they are stored as u64. https://github.com/rust-osdev/multiboot2-elf64/blob/master/src/memory_map.rs#L33.

For 32-bit kernels, this means that if a PC has more than 4GB of available RAM, we'll get some completely wrong values, and end up thinking that a range from `0x000000-0xXXXXXX` is available, wrecking havoc. Those should be sent to return u64s (which I did locally in my kernel), but that would be a breaking change.

**Comment by IsaacWoods** [comment]
Firstly, thanks for using the library and filing an issue!

We haven’t reached 1.0.0 yet, so breaking changes are unfortunate, but not the end of the world as far as I’m concerned. Since this is actually unsound on x86, I feel the breakage would be acceptable.

Feel free to open a PR, unless any of the rest of the team have any objections :)

**Comment by xacrimon** [comment]
I do not have any issue at all since we aren't at 1.0.0 Fine by me
